Repository onflow/flow-cli, pull requests merged in 2020-12, with the labels that each got.

#10 Add back contract deployment
  flow/accounts/create/create.go
Labels: Improvement

#12 Update to Emulator v0.12.5
  go.mod
  go.sum
Labels: Bugfix

#13 Add add-contract command
  flow/accounts/accounts.go
  flow/accounts/add-contract/add.go
Labels: Feature

#17 Set default service account key type to hex
  flow/config.go
Labels: Bugfix
