Repository onflow/flow-cli, pull requests merged in 2021-04, with the labels that each got.

#164 Update to Cadence v0.14.4, Go SDK v0.17.0, and Emulator v0.17.0
  go.mod
  go.sum
Labels: Improvement

#167 Shared Library - Tabwrite refactor
  internal/accounts/accounts.go
  internal/accounts/staking-info.go
  internal/blocks/blocks.go
  internal/collections/collections.go
  internal/command/result.go
  internal/config/init.go
  internal/events/events.go
  internal/keys/keys.go
  internal/scripts/scripts.go
  internal/status/status.go
  internal/transactions/transactions.go
  pkg/flowcli/util/utilities.go
Labels: Feature

#201 Bugfix keys generate
  internal/keys/keys.go
Labels: Bug

#183 Sign transaction refactor
  docs/build-transactions.md
  docs/send-signed-transactions.md
  docs/sign-transaction.md
  internal/transactions/build.go
  pkg/flowcli/services/transactions.go
  pkg/flowcli/util/utilities.go
Labels: Improvement

#171 Version check
  internal/command/command.go
Labels: Feature

#178 Account creation with multiple keys and non default key weights
  docs/create-accounts.md
Labels: Improvement

#215 Fix typos
  docs/account-add-contract.md
  docs/account-remove-contract.md
  docs/account-staking-info.md
  docs/account-update-contract.md
Labels: Documentation

#205 Default network without config
  internal/command/command.go
Labels: Improvement

#213 Global Configuration
  docs/initialize-configuration.md
  internal/command/command.go
  internal/config/init.go
  internal/emulator/start.go
  internal/project/init.go
  pkg/flowcli/config/config.go
  pkg/flowcli/config/loader.go
  pkg/flowcli/project/project.go
  pkg/flowcli/services/project.go
Labels: Improvement

#216 Remove multiple keys
  internal/command/command.go
  internal/emulator/start.go
  pkg/flowcli/config/config.go
  pkg/flowcli/config/config_test.go
  pkg/flowcli/config/json/account.go
  pkg/flowcli/config/json/account_test.go
  pkg/flowcli/config/json/config_test.go
  pkg/flowcli/config/loader_test.go
  pkg/flowcli/project/account.go
  pkg/flowcli/project/keys.go
  pkg/flowcli/project/project.go
  pkg/flowcli/project/project_test.go
  pkg/flowcli/project/transaction.go
Labels: Improvement
