Repository onflow/flow-cli, pull requests merged in 2021-08, with the labels that each got.

#343 Improve readme
  CONTRIBUTING.md
  README.md
  cli.gif
Labels: Documentation

#344 Updated documentation
  docs/get-events.md
Labels: Documentation

#347 fixes #345
  pkg/flowkit/gateway/emulator.go
  pkg/flowkit/services/scripts_test.go
  tests/resources.go
Labels: Improvement

#348 make loader accept the latest valid flow json in path
  go.sum
  internal/config/add-account.go
  internal/config/add-contract.go
  internal/config/add-deployment.go
  internal/config/add-network.go
  pkg/flowkit/config/config.go
  pkg/flowkit/config/loader.go
  pkg/flowkit/config/loader_test.go
Labels: Improvement

#350 Added errors to accessors methods in config
  go.mod
  go.sum
  internal/command/command.go
  pkg/flowkit/config/account.go
  pkg/flowkit/config/config.go
  pkg/flowkit/config/config_test.go
  pkg/flowkit/config/contract.go
  pkg/flowkit/config/json/account_test.go
  pkg/flowkit/config/json/config_test.go
  pkg/flowkit/config/json/contract_test.go
  pkg/flowkit/config/json/network_test.go
  pkg/flowkit/config/loader.go
  pkg/flowkit/config/loader_test.go
  pkg/flowkit/config/network.go
  pkg/flowkit/services/status.go
  pkg/flowkit/state.go
  pkg/flowkit/state_test.go
Labels: Improvement

#354 Documentation Fix
  docs/execute-scripts.md
Labels: Documentation

#355 Parse arguments without type hint
  internal/scripts/execute.go
  internal/transactions/send.go
  pkg/flowkit/arguments.go
  pkg/flowkit/arguments_test.go
Labels: Improvement

#360 Test Fix
  pkg/flowkit/config/loader_test.go
Labels: Bugfix

#358 Block include transaction IDs flag
  internal/blocks/get.go
Labels: Bugfix

#362 Documentation Updates
  README.md
  cli-banner.png
  cli-banner.svg
  docs/build-transactions.md
  docs/developer-updates/release-notes-v28.md
  docs/execute-scripts.md
  docs/send-transactions.md
Labels: Documentation

#363 Refactor config loading
  internal/config/add-account.go
  internal/config/add-contract.go
  internal/config/add-deployment.go
  internal/config/add-network.go
  internal/config/remove-account.go
  internal/config/remove-contract.go
  internal/config/remove-deployment.go
  internal/config/remove-network.go
  pkg/flowkit/config/config.go
  pkg/flowkit/config/loader.go
  pkg/flowkit/config/loader_test.go
  pkg/flowkit/state.go
  pkg/flowkit/state_test.go
Labels: Improvement

#364 Update docs with complex argument example
  docs/build-transactions.md
  docs/execute-scripts.md
  docs/send-transactions.md
Labels: Documentation

#366 Bugfix config cross-reference composition
  pkg/flowkit/config/json/config.go
  pkg/flowkit/config/json/config_test.go
  pkg/flowkit/config/loader.go
  pkg/flowkit/config/loader_test.go
Labels: Bug

#340 CD Improvements
  .github/workflows/cd.yml
Labels: Improvement

#374 Add Gas Limit Default
  pkg/flowkit/transaction.go
  version.txt
Labels: Bugfix

#375 Setup Go in CD for Snyk
  .github/workflows/cd.yml
Labels: Improvement
