Repository onflow/flow-cli, pull requests merged in 2021-06, with the labels that each got.

#270 Log Transaction ID
  pkg/flowcli/services/accounts.go
  pkg/flowcli/services/transactions.go
Labels: Improvement

#295 Update emulator version
  go.mod
  go.sum
  version.txt
Labels: Breaking Change, Improvement

#298 Release Version 0.23.0
  go.mod
  go.sum
  version.txt
Labels: Release

#269 Decode PEM public key
  docs/decode-keys.md
  internal/keys/decode.go
  internal/keys/keys.go
  pkg/flowcli/services/keys.go
  pkg/flowcli/services/keys_test.go
Labels: Feature

#271 Refactor event display
  internal/events/events.go
Labels: Bugfix

#274 Refactor Key Format
  docs/configuration.md
  docs/create-accounts.md
  docs/security.md
  docs/send-transactions.md
  internal/emulator/start.go
  pkg/flowcli/config/config.go
  pkg/flowcli/config/config_test.go
  pkg/flowcli/config/json/account.go
  pkg/flowcli/config/json/account_test.go
  pkg/flowcli/config/json/config_test.go
  pkg/flowcli/config/loader_test.go
  pkg/flowcli/config/parsers.go
  pkg/flowcli/config/processor_test.go
  pkg/flowcli/project/account.go
  pkg/flowcli/project/keys.go
  pkg/flowcli/project/project.go
  pkg/flowcli/project/project_test.go
  pkg/flowcli/project/transaction.go
  pkg/flowcli/services/accounts.go
  pkg/flowcli/services/project.go
  pkg/flowcli/services/transactions.go
Labels: Improvement

#277 Flow init warning
  internal/quick/init.go
Labels: Bugfix

#281 Updated Cobra to the latest version
  go.mod
  go.sum
Labels: Improvement

#284 Transaction ID
  pkg/flowcli/services/accounts.go
  pkg/flowcli/services/transactions.go
Labels: Improvement

#308 Upgrade to flow-emulator v0.22.0
  go.mod
  go.sum
Labels: Breaking Change

#317 Update Contract Bugfix
  internal/accounts/contract-update.go
Labels: Bugfix

#320 Documentation Improvements
  docs/configuration.md
Labels: Documentation
