Repository onflow/flow-cli, pull requests merged in 2021-03, with the labels that each got.

#94 ufix64 format fix
  flow/accounts/get/get.go
  flow/cli.go
  flow/result.go
Labels: Bug

#51 Pass arguments to scripts and transactions
  check-headers.sh
  flow/arguments.go
  flow/scripts/execute/execute.go
  flow/transactions/send/send.go
Labels: Feature

#108 Fix flaky non-deterministic test case (ConfigDeploymentsSimple)
  flow/project/cli/config/json/deploy_test.go
Labels: Bugfix

#113 Build darwin/arm64 binaries
  .github/workflows/ci.yml
  Makefile
Labels: Feature

#123 Suggested changes to command docs
  docs/account-add-contract.md
  docs/account-remove-contract.md
  docs/account-staking-info.md
  docs/account-update-contract.md
  docs/create-accounts.md
  docs/deploy-project-contracts.md
  docs/execute-scripts.md
  docs/generate-keys.md
  docs/get-accounts.md
  docs/get-blocks.md
  docs/get-collections.md
  docs/get-events.md
  docs/get-transactions.md
  docs/security.md
  docs/send-transactions.md
  docs/start-emulator.md
Labels: Documentation

#127 merged docs to CONTRIBUTING.md
  CONTRIBUTING.md
  docs/GUIDELINES.md
Labels: Documentation
