Repository onflow/flow-cli, pull requests merged in 2021-02, with the labels that each got.

#47 Update to Cadence v0.12.6, Go SDK v0.14.3, Flow Go v0.14.0, and Emulator v0.14.2
  go.mod
  go.sum
Labels: Improvement

#19 Add events
  cmd/flow/main.go
  flow/blocks/get/get.go
  flow/events/events.go
  flow/events/get/get.go
  flow/result.go
Labels: Feature

#73 readme fixes
  docs/initialize-project.md
Labels: Documentation

#85 Update Cadence v0.13.0, Go SDK v0.15.0, and Emulator v0.15.0
  go.mod
  go.sum
Labels: Improvement

#89 Update Cadence Language Server to v0.13.1
  go.mod
  go.sum
Labels: Bugfix, Improvement
