Repository onflow/flow-cli, pull requests merged in 2021-05, with the labels that each got.

#236 Increase grpc max message size to 16 mb
  pkg/flowcli/gateway/grpc.go
Labels: Improvement

#237 Update to Go SDK v0.19.0
  go.mod
  go.sum
  internal/keys/decode.go
  internal/keys/generate.go
  internal/keys/keys.go
  pkg/flowcli/config/parsers.go
  pkg/flowcli/services/keys.go
  pkg/flowcli/services/keys_test.go
  tests/e2e_test.go
Labels: Improvement

#240 Update cadence/languageserver to v0.15.2
  go.mod
  go.sum
Labels: Improvement

#244 JSON output fix
  internal/accounts/accounts.go
  internal/blocks/blocks.go
  internal/command/command.go
  internal/events/events.go
  internal/scripts/scripts.go
  internal/transactions/transactions.go
Labels: Bugfix

#253 Include and exclude flags support
  internal/accounts/accounts.go
  internal/accounts/contract-add.go
  internal/accounts/contract-remove.go
  internal/accounts/contract-update.go
  internal/accounts/create.go
  internal/accounts/get.go
  internal/blocks/blocks.go
  internal/blocks/get.go
  internal/command/command.go
  internal/command/result.go
  internal/config/init.go
  internal/keys/keys.go
  internal/status/status.go
  internal/transactions/get.go
  internal/transactions/send-signed.go
  internal/transactions/send.go
  internal/transactions/transactions.go
  pkg/flowcli/output/colors.go
  pkg/flowcli/output/emoji.go
  pkg/flowcli/output/logger.go
  pkg/flowcli/project/project.go
  pkg/flowcli/services/accounts.go
  pkg/flowcli/services/project.go
  pkg/flowcli/util/utilities.go
Labels: Improvement

#257 Decode keys reenabled
  docs/decode-keys.md
  internal/keys/decode.go
  internal/keys/keys.go
Labels: Improvement

#261 Enable config manage
  cmd/flow/main.go
  internal/config/config.go
  internal/project/project.go
  internal/quick/init.go
  pkg/flowcli/config/json/account.go
Labels: Feature

#255 Avoid checking version in dev
  internal/command/command.go
Labels: Improvement

#265 Update to Cadence v0.16.0 and Emulator v0.20.1
  go.mod
  go.sum
Labels: Improvement

#273 Update to Cadence v0.16.1 and Emulator v0.20.2
  go.mod
  go.sum
Labels: Improvement
