Repository onflow/flow-cli, pull requests merged in 2022-08, with the labels that each got.

#538 Interactive account creation for mainnet, testnet and emulator
  cmd/flow/main.go
  go.mod
  go.sum
  internal/accounts/create.go
  internal/command/command.go
  internal/keys/keys.go
  internal/transactions/send.go
  pkg/flowkit/account.go
  pkg/flowkit/config/account.go
  pkg/flowkit/config/config.go
  pkg/flowkit/config/json/account.go
  pkg/flowkit/config/json/account_test.go
  pkg/flowkit/config/json/config.go
  pkg/flowkit/config/json/config_test.go
  pkg/flowkit/config/json/emulator_test.go
  pkg/flowkit/config/loader.go
  pkg/flowkit/config/processor.go
  pkg/flowkit/events.go
  pkg/flowkit/go.mod
  pkg/flowkit/go.sum
  pkg/flowkit/keys.go
  pkg/flowkit/output/colors.go
  pkg/flowkit/output/emoji.go
  pkg/flowkit/output/logger.go
  pkg/flowkit/output/prompt.go
  pkg/flowkit/services/accounts.go
  pkg/flowkit/services/events.go
  pkg/flowkit/services/transactions_test.go
  pkg/flowkit/state.go
  pkg/flowkit/tests/fixtures.go
  pkg/flowkit/tests/resources.go
  pkg/flowkit/util/utilities.go
Labels: Feature, Developer Tool Team

#604 Fix gitignore method for interactive account creation
  pkg/flowkit/util/utilities.go
Labels: Bugfix

#596 Dependent issues action
  .github/workflows/dependent-issues.yml
Labels: Feature, Developer Tool Team

#607 Update emulator dependency to v0.34.0
  go.mod
  go.sum
Labels: Improvement

#609 Fix bug for setting metric settings
  .github/workflows/cd.yml
  Makefile
  internal/config/metrics-settings.go
  pkg/flowkit/util/mixpanel.go
Labels: Bugfix

#618 Update langauge server
  .gitignore
Labels: Improvement

#626 Pair Mixpanel tracking event with user distinct id
  pkg/flowkit/util/mixpanel.go
  pkg/flowkit/util/mixpanelEvent.go
  pkg/flowkit/util/mixpanelUser.go
Labels: Improvement

#625 Fix broken links in cli docs
  docs/complex-transactions.md
  docs/configuration.md
  docs/deploy-project-contracts.md
  docs/get-collections.md
  docs/index.md
  docs/initialize-configuration.md
Labels: Bugfix

#623 Resolve imports when deploying a contract
  go.mod
  go.sum
  internal/accounts/contract-add.go
  internal/accounts/contract-update.go
  pkg/flowkit/services/accounts.go
  pkg/flowkit/services/accounts_test.go
  pkg/flowkit/services/events_test.go
  pkg/flowkit/services/scripts_test.go
  pkg/flowkit/services/transactions_test.go
  pkg/flowkit/tests/resources.go
Labels: Improvement, Developer Tool Team

#630 Remove tracking token
  .github/workflows/cd.yml
  Makefile
  internal/command/command.go
  pkg/flowkit/util/mixpanel.go
Labels: Improvement, Developer Tool Team
