Repository onflow/flow-cli, pull requests merged in 2022-09, with the labels that each got.

#635 E2E Tests
  .github/workflows/ci.yml
  Makefile
  build/build.go
  e2e/e2e_test.go
  e2e/files/contract.cdc
  e2e/files/contractUpdated.cdc
  e2e/files/script.cdc
  e2e/files/tx.cdc
  e2e/utils/helpers.go
  go.mod
  go.sum
Labels: Test

#653 Update Dependencies
  go.mod
  go.sum
Labels: Improvement

#664 Update to Cadence v0.27.0 and Emulator v0.37.0
  go.mod
  go.sum
  internal/cadence/languageserver/languageserver.go
  pkg/flowkit/arguments.go
  pkg/flowkit/arguments_test.go
  pkg/flowkit/contracts/contracts.go
  pkg/flowkit/contracts/resolver.go
  pkg/flowkit/go.mod
  pkg/flowkit/go.sum
  pkg/flowkit/services/accounts_test.go
  pkg/flowkit/tests/resources.go
  pkg/flowkit/transaction.go
Labels: Improvement

#665 Add documentation for 'test' command
  docs/run-tests.md
Labels: dependent

#666 Update to go 1.19
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: Improvement

#661 Update version.txt
  version.txt
Labels: Release
