Repository onflow/flow-cli, pull requests merged in 2022-03, with the labels that each got.

#468 Update emulator
  go.mod
  go.sum
Labels: Improvement

#467 Integrate Dev Wallet
  cmd/flow/main.go
  docs/tools.md
  go.mod
  go.sum
  internal/tools/wallet.go
Labels: Feature

#473 Update FCL Dev Wallet Dependency
  go.mod
  go.sum
Labels: Bugfix

#472 Version 0.32.0 Release
  version.txt
Labels: Release

#480 Update Go version
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: Improvement

#481 update dependencies
  go.mod
  go.sum
Labels: Improvement

#482 Update fcl-dev wallet
  go.mod
  go.sum
  internal/tools/wallet.go
  version.txt
Labels: Improvement

#485 Emulator upgrade to v0.31.0
  go.mod
  go.sum
  version.txt
Labels: Breaking Change, Improvement
