Repository onflow/flow-cli, pull requests merged in 2022-06, with the labels that each got.

#513 Secure Cadence
  go.mod
  go.sum
  internal/cadence/cadence.go
  pkg/flowkit/arguments.go
  pkg/flowkit/config/json/deploy.go
  pkg/flowkit/contracts/contracts.go
  pkg/flowkit/contracts/resolver.go
  pkg/flowkit/services/accounts_test.go
  pkg/flowkit/services/blocks_test.go
  pkg/flowkit/transaction.go
  tests/fixtures.go
  version.txt
Labels: Release

#512 Handle panic from event parsing argument types that causes cli to crash
  internal/events/events.go
Labels: Bug, Bugfix

#516 Update Secure Cadence
  go.mod
  go.sum
  internal/blocks/blocks.go
  internal/command/result.go
  internal/events/events.go
  pkg/flowkit/arguments_test.go
  pkg/flowkit/config/config_test.go
  pkg/flowkit/config/json/account_test.go
  pkg/flowkit/config/json/config_test.go
  pkg/flowkit/config/json/contract_test.go
  pkg/flowkit/config/json/deploy_test.go
  pkg/flowkit/config/json/emulator_test.go
  pkg/flowkit/config/json/network_test.go
  pkg/flowkit/config/loader_test.go
  pkg/flowkit/config/processor_test.go
  pkg/flowkit/gateway/emulator.go
  pkg/flowkit/gateway/gateway.go
  pkg/flowkit/gateway/grpc.go
  pkg/flowkit/keys.go
  pkg/flowkit/services/accounts_test.go
  pkg/flowkit/services/blocks.go
  pkg/flowkit/services/events.go
  pkg/flowkit/services/events_test.go
  pkg/flowkit/services/scripts_test.go
  pkg/flowkit/services/transactions_test.go
  pkg/flowkit/state_test.go
  tests/gateway.go
  tests/mocks/Gateway.go
Labels: Improvement, Developer Tool Team

#525 Update to Emulator v0.33.2
  go.mod
  go.sum
Labels: Improvement

#526 Update to Cadence v0.24.3 and Go SDK 0.26.2
  go.mod
  go.sum
Labels: Improvement

#519 Update dev wallet v0.4.4
  go.mod
  go.sum
Labels: Improvement, Developer Tool Team

#517 Feature/Enable host configuration for dev wallet
  docs/tools.md
  internal/tools/wallet.go
Labels: Feature

#518 Bugfix/ use emulator service account defined in flow.json for signing default
  internal/transactions/send.go
Labels: Bugfix

#532 Release v0.37.0
  version.txt
Labels: Release
