Repository onflow/flow-cli, pull requests merged in 2022-11, with the labels that each got.

#639 Remove contract name for add and update contract commands
  build/build.go
  docs/account-add-contract.md
  docs/account-update-contract.md
  internal/accounts/contract-add.go
  internal/accounts/contract-update.go
  pkg/flowkit/contracts/resolver.go
  pkg/flowkit/contracts/resolver_test.go
  pkg/flowkit/services/accounts.go
Labels: Improvement

#682 Remove deprecated flags and arguments
  docs/build-transactions.md
  docs/execute-scripts.md
  docs/get-accounts.md
  docs/get-transactions.md
  docs/send-transactions.md
  docs/start-emulator.md
  internal/accounts/contract-add.go
  internal/accounts/contract-update.go
  internal/events/get.go
  internal/keys/generate.go
  internal/scripts/execute.go
  internal/transactions/build.go
  internal/transactions/send.go
  pkg/flowkit/arguments.go
Labels: Improvement

#684 Security code scanning
  .github/security_scan.yaml
Labels: Improvement

#694 Release process to two step
  .github/workflows/build-release.yaml
  .github/workflows/publish-release.yml
Labels: Improvement

#699 Add Sandbox Chain ID
  go.mod
  go.sum
  pkg/flowkit/config/parsers.go
  pkg/flowkit/go.mod
  pkg/flowkit/go.sum
  pkg/flowkit/util/utilities.go
Labels: Improvement

#693 Flowser explorer integration
  cmd/flow/main.go
  go.mod
  go.sum
  internal/command/command.go
  internal/settings/defaults.go
  internal/settings/metrics.go
  internal/settings/settings.go
  internal/tools/flowser.go
  pkg/flowkit/go.mod
  pkg/flowkit/go.sum
  pkg/flowkit/output/prompt.go
Labels: Feature

#697 Project deploy better error handling
  internal/project/deploy.go
  pkg/flowkit/services/accounts_test.go
  pkg/flowkit/services/project.go
  pkg/flowkit/services/project_test.go
Labels: Improvement

#706 Update dev-wallet 0.5.3
  go.mod
  go.sum
Labels: Improvement

#713 Add sandboxnet to default networks
  pkg/flowkit/config/network.go
Labels: Improvement

#715 Release process improvements
  .github/workflows/build-release.yaml
  .github/workflows/publish-release.yml
  .github/workflows/security_scan.yaml
  install.ps1
  install.sh
  run.ps1
  run.sh
Labels: Improvement

#712 Change default Flowser path on Windows
  go.mod
  go.sum
  internal/settings/defaults.go
  internal/tools/flowser.go
  pkg/flowkit/output/prompt.go
Labels: Improvement

#718 Update install documentation
  docs/install.md
Labels: Improvement

#721 Get block height each deploy itteration
  pkg/flowkit/services/project.go
Labels: Bug, Bugfix

#722 Update flow emulator to v0.40.0
  go.mod
  go.sum
  pkg/flowkit/go.mod
  pkg/flowkit/go.sum
Labels: Improvement
