Repository onflow/flow-cli, pull requests merged in 2022-07, with the labels that each got.

#544 Update docs with update section
  docs/install.md
Labels: Documentation, Developer Tool Team

#509 feature/prevent default emulator from being printed during project init in fl…
  docs/configuration.md
  pkg/flowkit/config/config.go
  pkg/flowkit/config/emulator.go
  pkg/flowkit/config/json/config.go
  pkg/flowkit/config/json/config_test.go
  pkg/flowkit/config/json/emulator.go
  pkg/flowkit/config/json/emulator_test.go
  pkg/flowkit/state.go
  pkg/flowkit/state_test.go
Labels: Feature

#577 Account creation improvements
  internal/accounts/create.go
  pkg/flowkit/account.go
  pkg/flowkit/config/account.go
  pkg/flowkit/config/json/account.go
  pkg/flowkit/config/loader.go
  pkg/flowkit/config/processor.go
  pkg/flowkit/output/colors.go
  pkg/flowkit/output/emoji.go
  pkg/flowkit/output/prompt.go
  pkg/flowkit/services/project.go
  pkg/flowkit/state.go
  pkg/flowkit/util/utilities.go
Labels: Developer Tool Team

#575 Update release template
  .github/release-drafter.yml
Labels: Documentation, Developer Tool Team
