Repository onflow/flow-cli, pull requests merged in 2022-01, with the labels that each got.

#439 Update staking-info command
  docs/account-staking-info.md
  docs/developer-updates/release-notes-v17.md
  internal/accounts/staking-info.go
  pkg/flowkit/gateway/grpc.go
  pkg/flowkit/services/accounts.go
  pkg/flowkit/services/accounts_test.go
  pkg/flowkit/values.go
Labels: Bugfix

#442 Clean outdated Homebrew
  homebrew-bottle.png
  homebrew.md
Labels: Improvement

#440 Khalil/1652 download protocol snapshot
  Makefile
  cmd/flow/main.go
  docs/snapshot-save.md
  internal/snapshot/save.go
  internal/snapshot/snapshot.go
  pkg/flowkit/gateway/emulator.go
  pkg/flowkit/gateway/gateway.go
  pkg/flowkit/gateway/grpc.go
  pkg/flowkit/services/services.go
  pkg/flowkit/services/snapshot.go
  tests/mocks/Gateway.go
Labels: Feature

#445 Documentation Updates
  docs/account-add-contract.md
  docs/account-remove-contract.md
  docs/account-staking-info.md
  docs/account-update-contract.md
  docs/build-transactions.md
  docs/complex-transactions.md
  docs/get-blocks.md
  internal/accounts/contract-add.go
  internal/accounts/contract-remove.go
  internal/accounts/contract-update.go
  internal/accounts/get.go
  internal/blocks/get.go
  internal/transactions/get.go
  internal/transactions/send-signed.go
  internal/transactions/sign.go
Labels: Documentation

#444 Bugfix transaction multiple function declaration
  pkg/flowkit/services/transactions_test.go
  pkg/flowkit/transaction.go
  tests/resources.go
Labels: Bugfix
