Repository onflow/flow-cli, pull requests merged in 2023-06, with the labels that each got.

#1057 Add Hybrid Custody scaffold
  scaffolds.json
Labels: Feature

#1066 Update hybrid-custody-scaffold commit
  scaffolds.json
Labels: Improvement

#1068 Update to Cadence v0.39.4
  flowkit/flowkit_test.go
  flowkit/gateway/emulator.go
  flowkit/gateway/mocks/Gateway.go
  flowkit/go.mod
  flowkit/go.sum
  flowkit/mocks/Services.go
  go.mod
  go.sum
  internal/cadence/cadence.go
  internal/emulator/start.go
Labels: dependencies

#1075 Return an exit code of 1 for test scripts with failures
  cmd/flow/main.go
  internal/command/command.go
  internal/test/test.go
Labels: Improvement

#1082 Isolate flow dev contract removal/update logic
  flowkit/flowkit.go
  internal/super/project.go
Labels: Improvement

#1084 Update web dapp scaffold to 0.3.0
  scaffolds.json
Labels: Improvement

#1090 Support LCOV format for code coverage
  flowkit/go.mod
  flowkit/go.sum
  go.mod
  go.sum
  internal/test/test.go
Labels: Feature

#1101 Update flowkit to Cadence v0.39.12
  flowkit/go.mod
  flowkit/go.sum
  go.mod
  go.sum
Labels: Improvement

#1102 Update to Cadence v0.39.12
  go.mod
  go.sum
Labels: dependencies

#1110 Remove contract also removes from flow.json deployments
  flowkit/config/deployment.go
  flowkit/mocks/Services.go
  internal/accounts/contract-remove.go
  internal/util/prompt.go
Labels: Improvement
