Repository onflow/flow-cli, pull requests merged in 2023-02, with the labels that each got.

#825 Release v0.45.1
  version.txt
Labels: Release

#824 Refactor metrics and include version
  go.mod
  go.sum
  internal/command/command.go
  internal/emulator/start.go
  internal/settings/settings.go
  pkg/flowkit/util/mixpanel.go
  pkg/flowkit/util/mixpanelEvent.go
Labels: Improvement

#832 Update build action to new mixpanel location
  .github/workflows/build-release.yaml
Labels: Improvement

#831 Bugfix remove new line in the filter output
  internal/command/result.go
Labels: Bugfix

#834 Update configuration.md
  docs/configuration.md
Labels: Documentation

#830 Update send transaction example
  docs/build-transactions.md
  docs/send-transactions.md
Labels: Documentation

#837 Reference scaffolds by commit hashes
  CONTRIBUTING.md
  internal/super/setup.go
  scaffolds.json
Labels: Improvement

#852 Update version.txt to v0.45.4
  version.txt
Labels: Release

#851 Specify account key from a file location
  docs/configuration.md
  docs/security.md
  pkg/flowkit/account.go
  pkg/flowkit/config/account.go
  pkg/flowkit/config/config.go
  pkg/flowkit/config/json/account.go
  pkg/flowkit/config/json/account_test.go
  pkg/flowkit/config/loader_test.go
  pkg/flowkit/config/processor.go
  pkg/flowkit/config/processor_test.go
  pkg/flowkit/keys.go
Labels: Improvement

#853 Account creation using APIs
  .github/workflows/build-release.yaml
  .gitignore
  docs/create-accounts.md
  go.mod
  go.sum
  internal/accounts/create-interactive.go
  internal/accounts/create.go
  pkg/flowkit/go.mod
  pkg/flowkit/go.sum
  pkg/flowkit/output/prompt.go
  pkg/flowkit/transaction.go
  pkg/flowkit/util/utilities.go
Labels: Improvement

#860 Alternative to a required cadence folder when using dev command
  internal/super/files.go
Labels: Improvement

#867 Change const to var for build variables
  internal/accounts/create-interactive.go
Labels: Bugfix

#854 Improve scaffold description
  scaffolds.json
Labels: Documentation

#869 Use API for account creation
  .github/workflows/build-release.yaml
  Makefile
  go.mod
  go.sum
  internal/accounts/create-interactive.go
  pkg/flowkit/go.mod
  pkg/flowkit/go.sum
  pkg/flowkit/transaction.go
Labels: Improvement

#871 Refactor contract aliases
  internal/config/add-contract.go
  internal/super/project.go
  pkg/flowkit/CHANGELOG.md
  pkg/flowkit/config/config.go
  pkg/flowkit/config/config_test.go
  pkg/flowkit/config/contract.go
  pkg/flowkit/config/json/contract.go
  pkg/flowkit/config/json/contract_test.go
  pkg/flowkit/config/loader.go
  pkg/flowkit/config/parsers.go
  pkg/flowkit/project/contract.go
  pkg/flowkit/project/deployment.go
  pkg/flowkit/project/imports.go
  pkg/flowkit/services/project.go
  pkg/flowkit/services/project_test.go
  pkg/flowkit/services/scripts_test.go
  pkg/flowkit/services/tests_test.go
  pkg/flowkit/services/transactions_test.go
  pkg/flowkit/state.go
  pkg/flowkit/state_test.go
  pkg/flowkit/tests/testnet_test.go
Labels: Improvement

#872 Bugfix dev not supporting aliases
  internal/super/project.go
Labels: Improvement

#873 Update basic scaffold to latest
  scaffolds.json
Labels: Improvement

#876 Add a new empty scaffold
  internal/super/setup.go
  scaffolds.json
Labels: Improvement
