Repository onflow/flow-cli, pull requests merged in 2023-03, with the labels that each got.

#887 Scaffolds within specified folders supporting Unity scaffold
  internal/super/setup.go
  scaffolds.json
Labels: Feature

#919 Update to Cadence v0.36.0
  go.mod
  go.sum
  pkg/flowkit/go.mod
  pkg/flowkit/go.sum
Labels: dependencies

#923 Bugfix env replacement
  pkg/flowkit/config/account.go
  pkg/flowkit/config/json/account.go
  pkg/flowkit/config/loader_test.go
  pkg/flowkit/config/processor.go
  pkg/flowkit/config/processor_test.go
Labels: Bugfix

#926 Return signature algorithm on key generation
  internal/keys/decode.go
  internal/keys/generate.go
  internal/keys/keys.go
Labels: Improvement

#936 Fix: improve import parsing regex
  pkg/flowkit/project/program.go
  pkg/flowkit/project/program_test.go
Labels: Bug

#908 Feature: Show contract diff on contract update deployment
  go.mod
  go.sum
  internal/accounts/contract-add.go
  internal/accounts/contract-update.go
  internal/project/deploy.go
  internal/super/project.go
  pkg/flowkit/go.mod
  pkg/flowkit/go.sum
  pkg/flowkit/output/prompt.go
  pkg/flowkit/services/accounts.go
  pkg/flowkit/services/accounts_test.go
  pkg/flowkit/services/events_test.go
  pkg/flowkit/services/project.go
  pkg/flowkit/services/project_test.go
  pkg/flowkit/services/scripts_test.go
  pkg/flowkit/services/transactions_test.go
  pkg/flowkit/tests/testnet_test.go
Labels: Feature

#937 Update security scann
  .github/workflows/security_scan.yaml
Labels: Improvement

#938 Fixate scaffold order
  internal/super/setup.go
  pkg/flowkit/output/prompt.go
Labels: Bugfix

#950 Bugfix ENV parsing
  pkg/flowkit/config/json/account.go
  pkg/flowkit/config/json/account_test.go
  pkg/flowkit/config/loader_test.go
Labels: Bugfix

#940 Remove deprecated option
  docs/security.md
Labels: Documentation

#951 Add snapshot documentation
  docs/emulator-snapshot.md
Labels: Documentation
