Repository onflow/flow-cli, pull requests merged in 2023-08, with the labels that each got.

#1158 Update to Cadence v0.40.0
  flowkit/go.mod
  flowkit/go.sum
  go.mod
  go.sum
Labels: Improvement

#1171 Remove gitleaks
  .github/workflows/security_scan.yaml
Labels: github_actions

#1166 Use custom flag if no state is available
  internal/command/command.go
Labels: Bug

#1167 Update to latest stable cadence
  .github/workflows/ci.yml
  CONTRIBUTING.md
  flowkit/arguments/arguments_test.go
  flowkit/flowkit_test.go
  flowkit/gateway/mocks/Gateway.go
  flowkit/go.mod
  flowkit/go.sum
  flowkit/mocks/Services.go
  flowkit/project/deployment_test.go
  flowkit/project/imports_test.go
  flowkit/project/program_test.go
  flowkit/state_test.go
  flowkit/tests/resources.go
  flowkit/tests/testnet_test.go
  flowkit/transactions/transaction_test.go
  go.mod
  go.sum
  internal/test/test_test.go
Labels: Improvement

#1177 [flowkit] Update cadence version to v0.41.0-stable-cadence.1
  flowkit/go.mod
  flowkit/go.sum
  go.mod
  go.sum
Labels: Improvement
