Repository onflow/flow-cli, pull requests merged in 2023-04, with the labels that each got.

#963 Use service account key for flow dev account gen
  internal/super/project.go
Labels: Improvement

#975 Fix dev wallet crashing when key is in separate file
  internal/tools/wallet.go
Labels: Bug

#983 Contract removal with dev command and add tests
  internal/super/project.go
  pkg/flowkit/config/contract.go
  pkg/flowkit/config/contract_test.go
Labels: Bug

#980 Persist user created accounts
  internal/super/dev.go
  internal/super/project.go
Labels: Bug

#987 Remove contract from emulator on deletion
  internal/super/project.go
Labels: Improvement

#994 Fix building binaries actions
  Makefile
  flowkit/go.mod
  go.sum
Labels: Bugfix

#1001 Add show diff flag to update-contract command and fix regression
  internal/accounts/contract-add.go
  internal/project/deploy.go
  internal/util/prompt.go
Labels: Bug, Improvement

#1008 Add show diff flag to update contract docs
  docs/account-update-contract.md
Labels: Documentation
