Repository onflow/flow-cli, pull requests merged in 2023-01, with the labels that each got.

#767 Update ps install script
  install.ps1
Labels: Improvement

#765 Add validation of monotonic addresses
  pkg/flowkit/config/parsers.go
  pkg/flowkit/config/parsers_test.go
Labels: Bugfix

#763 Fix project deploy edge case with account key sequence
  go.mod
  go.sum
  internal/accounts/contract-add.go
  internal/accounts/contract-remove.go
  internal/accounts/contract-update.go
  pkg/flowkit/services/accounts.go
  pkg/flowkit/services/accounts_test.go
  pkg/flowkit/services/events_test.go
  pkg/flowkit/services/project.go
  pkg/flowkit/services/project_test.go
  pkg/flowkit/services/scripts_test.go
  pkg/flowkit/services/transactions_test.go
  pkg/flowkit/tests/resources.go
  pkg/flowkit/tests/testnet_test.go
Labels: Improvement

#781 Check if contract exists before removing
  pkg/flowkit/services/accounts.go
  pkg/flowkit/services/accounts_test.go
Labels: Improvement

#782 Update langauge server to v0.6.1
  go.mod
  go.sum
Labels: Improvement

#735 Add and remove contract to deployment
  pkg/flowkit/config/deployment.go
  pkg/flowkit/config/deployment_test.go
Labels: Improvement

#731 Setup supercommand
  CONTRIBUTING.md
  cmd/flow/main.go
  go.mod
  internal/app/app.go
  internal/app/create.go
  internal/super/setup.go
  pkg/flowkit/output/prompt.go
  scaffolds.json
Labels: Feature

#774 Add documentation for super commands
  docs/super-commands.md
Labels: Documentation

#734 Dev supercommand
  cmd/flow/main.go
  go.mod
  go.sum
  internal/project/deploy.go
  internal/super/dev.go
  internal/super/files.go
  internal/super/files_test.go
  internal/super/output.go
  internal/super/project.go
  pkg/flowkit/account.go
  pkg/flowkit/config/deployment.go
  pkg/flowkit/go.mod
  pkg/flowkit/output/colors.go
  pkg/flowkit/project/deployment.go
  pkg/flowkit/project/imports.go
  pkg/flowkit/project/imports_test.go
  pkg/flowkit/project/program.go
  pkg/flowkit/project/program_test.go
  pkg/flowkit/services/accounts.go
  pkg/flowkit/services/project.go
  pkg/flowkit/services/scripts_test.go
  pkg/flowkit/services/services.go
  pkg/flowkit/state.go
  pkg/flowkit/transaction.go
Labels: Feature

#799 Deploy ignore non-existing contract
  pkg/flowkit/services/project.go
Labels: Improvement

#804 Update dev error regex
  internal/super/output.go
Labels: Bugfix

#805 Update scaffolds to only include compatible ones
  scaffolds.json
Labels: Improvement

#814 Dev clean state improvement
  internal/super/dev.go
  internal/super/project.go
Labels: Improvement

#816 Handle file renaming using dev command
  internal/project/deploy.go
  internal/super/files.go
  internal/super/project.go
  pkg/flowkit/state.go
Labels: Improvement

#822 Fix project aliases resolving with new import schema
  pkg/flowkit/project/contract.go
  pkg/flowkit/project/deployment.go
  pkg/flowkit/project/deployment_test.go
  pkg/flowkit/project/program_test.go
  pkg/flowkit/services/project.go
  pkg/flowkit/services/project_test.go
  pkg/flowkit/state.go
  pkg/flowkit/state_test.go
  pkg/flowkit/tests/resources.go
Labels: Bugfix

#823 Bugfix output filter by key
  internal/command/result.go
Labels: Bugfix
