Repository onflow/flow-cli, pull requests merged in 2023-10, with the labels that each got.

#1235 Update hybrid-custody-scaffold commit hash
  scaffolds.json
Labels: Improvement

#1244 Bump default scaffold version to include ViewResolver in flow.json
  scaffolds.json
Labels: Improvement

#1247 Adding a contract to deployment section when using flowkit.AddContract
  flowkit/flowkit.go
  flowkit/flowkit_test.go
Labels: Bug, go

#1242 Add generate templates command
  README.md
  cmd/flow/main.go
  flowkit/state.go
  internal/super/generate.go
  internal/super/generate_test.go
Labels: Feature
