Repository onflow/flow-cli, pull requests merged in 2024-05, with the labels that each got.

#1555 Fix Windows tests
  .github/workflows/ci.yml
  Makefile
  internal/super/generate_test.go
  internal/transactions/transactions_test.go
  internal/util/util.go
Labels: Improvement

#1558 Improve emojis across Windows versions in Dependency Manager outputs
  internal/dependencymanager/dependencyinstaller.go
Labels: Improvement

#1561 Add message if conflicting contract on dependency install
  internal/dependencymanager/dependencyinstaller.go
Labels: Feature

#1550 Default `flow test` behaviour to test `**/*_test.cdc`
  internal/test/test.go
Labels: Improvement

#1595 Upgrade flowkit
  go.mod
  go.sum
  internal/accounts/create-interactive.go
  internal/cadence/lint_test.go
  internal/config/init.go
  internal/dependencymanager/install.go
  internal/emulator/start.go
  internal/super/flix_test.go
  internal/util/test.go
Labels: dependencies

#1582 Cadence 1.0 Multi-Staging
  internal/cadence/lint.go
  internal/migrate/get_staged_code.go
  internal/migrate/get_staged_code_test.go
  internal/migrate/is_validated.go
  internal/migrate/is_validated_test.go
  internal/migrate/migrate.go
  internal/migrate/mock_git_hub_repositories_service_test.go
  internal/migrate/mock_staging_service_test.go
  internal/migrate/mock_staging_validator_test.go
  internal/migrate/stage.go
  internal/migrate/stage_contract.go
  internal/migrate/stage_contract_test.go
  internal/migrate/stage_test.go
  internal/migrate/staging_service.go
  internal/migrate/staging_service_test.go
  internal/migrate/staging_validator.go
  internal/migrate/staging_validator_test.go
  internal/migrate/unstage_contract_test.go
  internal/util/util.go
Labels: Improvement

#1598 Only ask for deployments and aliases once
  internal/dependencymanager/dependencyinstaller.go
  internal/dependencymanager/dependencyinstaller_test.go
Labels: Bug

#1547 add contract migration check on all calls
  cmd/flow/main.go
  internal/command/command.go
  internal/migrate/get_staged_code.go
  internal/migrate/is_staged.go
  internal/migrate/is_validated.go
  internal/migrate/is_validated_test.go
  internal/migrate/list_staged_contracts.go
  internal/migrate/migrate.go
  internal/migrate/stage.go
  internal/migrate/state.go
  internal/migrate/unstage_contract.go
  internal/migrate/validator/mocks/git_hub_repositories_service.go
  internal/migrate/validator/validator.go
  internal/util/util.go
Labels: Feature

#1603 Gracefully recover from contract update validation errors
  internal/migrate/stage.go
  internal/migrate/staging_service.go
  internal/migrate/staging_validator.go
Labels: Improvement

#1607 Handle transaction result errors in `flow migrate stage`
  internal/migrate/staging_service.go
  internal/migrate/staging_service_test.go
Labels: Improvement

#1611 Revert flow dev running emulator
  internal/super/dev.go
Labels: Bug

#1616 Switch `init` to an interactive setup
  cmd/flow/main.go
  go.mod
  go.sum
  internal/accounts/contract-add.go
  internal/accounts/contract-remove.go
  internal/accounts/create-interactive.go
  internal/command/command.go
  internal/config/add-account.go
  internal/config/add-contract.go
  internal/config/add-deployment.go
  internal/config/add-network.go
  internal/config/config.go
  internal/config/init.go
  internal/config/remove-account.go
  internal/config/remove-contract.go
  internal/config/remove-deployment.go
  internal/config/remove-network.go
  internal/dependencymanager/add.go
  internal/dependencymanager/dependencyinstaller.go
  internal/dependencymanager/dependencyinstaller_test.go
  internal/dependencymanager/install.go
  internal/project/deploy.go
  internal/prompt/prompt.go
  internal/prompt/select-options.go
  internal/prompt/text-input.go
  internal/super/generate.go
  internal/super/generate_test.go
  internal/super/scaffolds.go
  internal/super/setup.go
  internal/super/templates/contract_counter.cdc.tmpl
  internal/super/templates/script_counter.cdc.tmpl
  internal/super/templates/transaction_counter.cdc.tmpl
  internal/tools/flowser.go
  internal/transactions/build.go
  internal/transactions/send-signed.go
  internal/transactions/sign.go
  internal/util/files.go
Labels: Feature
