Repository onflow/flow-cli, pull requests merged in 2024-02, with the labels that each got.

#1356 Switch `feature/stable-cadence` branch to Cadence 1.0 FCL Dev Wallet
  go.mod
  go.sum
Labels: dependencies, Cadence 1.0

#1389 Format boilerplat access modifiers
  internal/super/generate.go
  internal/super/generate_test.go
Labels: Improvement

#1391 Remove os dir code in `generate` tests
  internal/super/generate_test.go
Labels: Improvement

#1401 Update url for Cadence 1.0 migration guide
  cmd/flow/main.go
Labels: Improvement

#1423 Switch to goreleaser & add support for CGO cross-compilation
  .github/workflows/build-release.yaml
  .gitignore
  .goreleaser.yaml
  Makefile
  go.mod
  go.sum
Labels: Improvement

#1432 Add Previewnet network
  go.mod
  go.sum
  internal/config/add-contract.go
  internal/dependencymanager/dependencyinstaller.go
  internal/dependencymanager/dependencyinstaller_test.go
  internal/util/prompt.go
  internal/util/util.go
Labels: Feature
