Repository onflow/flow-cli, pull requests merged in 2024-03, with the labels that each got.

#1434 Add `v` prefix back to build assets
  .goreleaser.yaml
Labels: Improvement

#1438 Bump flowkit to v1.16.0 and fix breaking changes
  go.mod
  go.sum
  internal/dependencymanager/dependencyinstaller.go
  internal/dependencymanager/dependencyinstaller_test.go
  internal/snapshot/save.go
Labels: dependencies

#1440 Port Go-Releaser changes to `master`
  .github/workflows/build-release.yaml
  .gitignore
  .goreleaser.yaml
  Makefile
  go.mod
  go.sum
Labels: Improvement

#1441 Upgrade flowkit to v0.17.0
  go.mod
  go.sum
Labels: dependencies

#1442 Fix broken build
  .goreleaser.yaml
  Makefile
  go.mod
  go.sum
Labels: Improvement

#1439 Start emulator on `flow dev` with flag
  .github/workflows/ci.yml
  go.mod
  internal/super/dev.go
Labels: Feature

#1426 Add `flow migrate state` command
  go.mod
  go.sum
  internal/migrate/migrate.go
  internal/migrate/state.go
  internal/migrate/state_test.go
Labels: Feature

#1451 Generate contract test file along with contract boilerplate
  internal/super/generate.go
  internal/super/generate_test.go
Labels: Feature

#1448 Add `flow cadence lint` command
  cmd/flow/main.go
  go.mod
  go.sum
  internal/cadence/cadence.go
  internal/cadence/lint.go
  internal/cadence/lint_test.go
  internal/cadence/linter.go
  internal/cadence/stdlib.go
  internal/command/command.go
  internal/command/result.go
  internal/test/test.go
Labels: Feature

#1466 Switch hardcoded Mainnet contracts check to use system contracts library
  go.sum
  internal/project/deploy.go
Labels: Improvement

#1476 Support previewnet for `accounts create`
  internal/accounts/create-interactive.go
Labels: Improvement

#1469 Add Cadence V0.42->V1.0 Update Checker to staging
  internal/cadence/linter.go
  internal/migrate/stage_contract.go
  internal/migrate/stage_contract_test.go
  internal/migrate/staging_validator.go
  internal/migrate/staging_validator_test.go
  internal/util/stdlib.go
Labels: Improvement
