Repository onflow/flow-cli, pull requests merged in 2024-01, with the labels that each got.

#1329 Add Cadence 1.0 messaging
  cmd/flow/main.go
Labels: Improvement

#1342 Move Cadence 1.0 Warning to os.Stderr
  cmd/flow/main.go
Labels: Improvement

#1347 add support for getting transactions and results from emulator by block id
  flowkit/gateway/emulator.go
Labels: Improvement

#1319 `add` and `install` from live networks with dependency manager
  .gitignore
  cmd/flow/main.go
  flowkit/config/config.go
  flowkit/config/contract.go
  flowkit/config/contract_test.go
  flowkit/config/dependency.go
  flowkit/config/dependency_test.go
  flowkit/config/json/config.go
  flowkit/config/json/contract.go
  flowkit/config/json/dependency.go
  flowkit/config/json/dependency_test.go
  flowkit/config/loader.go
  flowkit/config/processor.go
  flowkit/gateway/mocks/Gateway.go
  flowkit/mocks/Services.go
  flowkit/project/program.go
  flowkit/project/program_test.go
  flowkit/schema.json
  flowkit/state.go
  flowkit/state_test.go
  flowkit/tests/resources.go
  internal/dependencymanager/add.go
  internal/dependencymanager/dependencies.go
  internal/dependencymanager/dependencyinstaller.go
  internal/dependencymanager/dependencyinstaller_test.go
  internal/dependencymanager/install.go
  internal/util/prompt.go
Labels: Feature

#1354 Coverage report map contract files
  flowkit/state.go
  internal/test/test.go
  internal/test/test_test.go
Labels: Improvement

#1337 emulator private key file
  flowkit/accounts/account.go
  flowkit/accounts/keys.go
  flowkit/accounts/keys_test.go
  flowkit/state.go
  flowkit/transactions/transaction_test.go
  internal/accounts/create-interactive.go
Labels: Improvement

#1364 Fix command message for config add
  internal/dependencymanager/add.go
Labels: Improvement

#1366 Update Stable Cadence feature branch to Cadence v1.0.0-M4
  flowkit/gateway/mocks/Gateway.go
  flowkit/go.mod
  flowkit/go.sum
  flowkit/mocks/Services.go
  go.mod
  go.sum
  internal/super/flix_test.go
  internal/super/generate.go
  internal/super/generate_test.go
  internal/test/test_test.go
Labels: dependencies
