Repository onflow/flow-cli, pull requests merged in 2024-04, with the labels that each got.

#1490 Fix `flow version` output bug
  cmd/flow/main.go
  internal/version/version.go
Labels: Improvement

#1494 Update to Cadence v1.0.0-preview.19
  go.mod
  go.sum
Labels: dependencies

#1495 Fix staging validator type change bug
  internal/migrate/stage_contract.go
  internal/migrate/staging_validator.go
Labels: Bug

#1496 Add check for latest Cadence 1.0 release
  internal/command/command.go
Labels: Improvement

#1501 Add missing `is-validated` command
  internal/migrate/migrate.go
Labels: Improvement

#1504 Generate standard files with `setup` command
  .github/workflows/ci.yml
  go.mod
  go.sum
  internal/config/init.go
  internal/super/generate.go
  internal/super/generate_test.go
  internal/super/scaffolds.go
  internal/super/setup.go
  internal/super/setup_test.go
Labels: Feature

#1507 Add mainnet `MigrationContractStaging` address
  internal/migrate/migrate.go
Labels: Improvement

#1497 Use type change checker from `flow-go`
  internal/migrate/staging_validator.go
Labels: Improvement

#1513 Update to latest Cadence Language Server
  go.mod
  go.sum
Labels: Improvement

#1518 Update EVM Gateway to latest version & add Previewnet chain ID
  go.mod
  go.sum
  internal/evm/gateway.go
Labels: Improvement

#1523 Fix `access(account)` bug in contract update validator
  internal/migrate/staging_validator.go
  internal/migrate/staging_validator_test.go
Labels: Improvement

#1530 Fix embedded flags issue when running Dependency Manager flags manually
  internal/dependencymanager/add.go
  internal/dependencymanager/dependencyinstaller.go
Labels: Bug

#1536 Add message to clarify no updates when none to Dependency Manager
  internal/dependencymanager/add.go
  internal/dependencymanager/dependencyinstaller.go
  internal/dependencymanager/install.go
  internal/util/emoji.go
Labels: Improvement

#1539 Fix bug from `flow deps add` command missing Flags field
  internal/dependencymanager/add.go
Labels: Improvement
