Repository onflow/flow-cli, pull requests merged in 2025-09, with the labels that each got.

#2033 Allow use of `flow init` for existing directories
  cmd/flow/main.go
  internal/super/init.go
  internal/super/init_utils.go
Labels: Improvement

#2035 Add styling to flow root command, results, and test output
  cmd/flow/main.go
  common/branding/branding.go
  internal/command/result.go
  internal/command/template.go
  internal/prompt/select.go
  internal/prompt/textinput.go
  internal/super/init.go
  internal/test/test.go
Labels: Improvement

#2066 Fix: respect termination in `flow init` prompt
  internal/dependencymanager/dependencyinstaller.go
  internal/prompt/prompt.go
  internal/super/init.go
Labels: Bug

#2082 Add `flow accounts list` to show account validity, network & balance
  internal/accounts/accounts.go
  internal/accounts/list.go
  internal/util/util.go
Labels: Feature

#2092 Add tx alias for transactions subcommand #2086
  internal/transactions/transactions.go
Labels: Improvement

#2099 Support funding emulator accounts with `flow accounts fund`
  internal/accounts/fund.go
  internal/accounts/fund_test.go
  internal/accounts/list.go
  internal/dependencymanager/discover.go
  internal/util/accounts.go
  internal/util/accounts_test.go
  internal/util/util.go
Labels: Feature

#2091 Add Scheduled Transactions starter project option to `flow init`
  internal/dependencymanager/dependencyinstaller.go
  internal/dependencymanager/dependencyinstaller_test.go
  internal/super/generator/contract_template.go
  internal/super/generator/generator.go
  internal/super/generator/templates/README_scheduled_transactions.md.tmpl
  internal/super/generator/templates/contract_counter_transaction_handler.cdc.tmpl
  internal/super/generator/templates/contract_counter_transaction_handler_test.cdc.tmpl
  internal/super/generator/templates/cursor/agent_rules.mdc.tmpl
  internal/super/generator/templates/cursor/flip.md.tmpl
  internal/super/generator/templates/cursor/index.md.tmpl
  internal/super/generator/templates/cursor/quick_checklist.md.tmpl
  internal/super/generator/templates/transaction_init_counter_transaction_handler.cdc.tmpl
  internal/super/generator/templates/transaction_init_schedule_manager.cdc.tmpl
  internal/super/generator/templates/transaction_schedule_increment_counter.cdc.tmpl
  internal/super/init.go
  internal/super/init_utils.go
  internal/super/projecttypes.go
Labels: Feature
